export const GET_GLOBAL_ARTICLES = 'GET_GLOBAL_ARTICLES';
export const CHANGE_ACTUAL_PAGE = 'CHANGE_ACTUAL_PAGE';
export const USER_LOG_IN = 'USER_LOG_IN';
export const GET_AN_ARTICLE = 'GET_AN_ARTICLE';
export const USER_LOG_OUT = 'USER_LOG_OUT';
export const SET_ERROR = 'SET_ERROR';
